project_id = "myqgnnqltemfpzdxwybj"

[functions.process-files]
verify_jwt = false

[functions.upscale-image]
verify_jwt = true

[functions.edit-image-gemini]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.manage-subscription]
verify_jwt = true